name: backend-cicd
on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'docker.io/kyubeanshin/trading-api:latest' }}
  NAMESPACE:  ${{ vars.K8S_NAMESPACE || 'skala-practice' }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY || 'docker.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

deploy:
  needs: build_and_push
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      if: ${{ secrets.KUBE_CONFIG != '' }}

    - uses: azure/setup-kubectl@v4
      if: ${{ secrets.KUBE_CONFIG != '' }}

    - name: Write kubeconfig
      if: ${{ secrets.KUBE_CONFIG != '' }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBE_CONFIG}" > $HOME/.kube/config
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    - name: Apply K8s manifests
      if: ${{ secrets.KUBE_CONFIG != '' }}
      run: |
        sed -i "s#DOCKER_IMAGE_PLACEHOLDER#${{ env.IMAGE_NAME }}#g" k8s/deploy.yaml
        kubectl -n ${{ env.NAMESPACE }} apply -f k8s/deploy.yaml
        kubectl -n ${{ env.NAMESPACE }} apply -f k8s/ingress.yaml

