name: backend-cicd
on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'docker.io/yourid/trading-api:latest' }}
  NAMESPACE:  ${{ vars.K8S_NAMESPACE || 'skala-practice' }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY || 'docker.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Write kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBE_CONFIG}" > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Apply K8s manifests
        run: |
          sed -i "s#DOCKER_IMAGE_PLACEHOLDER#${IMAGE_NAME}#g" k8s/deploy.yaml
          kubectl -n ${NAMESPACE} apply -f k8s/deploy.yaml
          kubectl -n ${NAMESPACE} apply -f k8s/ingress.yaml
